owner: MigraineKR
repo: khs.status

sites:
  - name: headache.or.kr
    url: https://www.headache.or.kr/index.php
  - name: migrainecluster.com
    url: http://www.migrainecluster.com/
  - name: headache_m.one-page.co.kr
    url: http://headache_m.one-page.co.kr/
        
status-website:
  cname: khs.status.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | KHS
  introTitle: "**Status** for Korean Headache Society"
  introMessage: 대한두통학회 웹모니터
  navbar:
    - title: Status
      href: /
    - title: YouTube
      href: https://www.youtube.com/@headache-kr
    - title: Hospital
      href: http://www.migrainecluster.com/search/lists/all

